projects:
  spotfiyappapi:
    schemaPath: ../../../../../../../graphql/schema.json
    includes:
      - ''
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: /graphql
extensions:
  amplify:
    version: 3
